### ISSUE TITLE
Cannot find module 'haraka-test-fixtures'

### ISSUE THREAD

**Issue by Manishjodhani** [haraka/haraka-plugin-syslog#16] opened 2018-04-13 12:00 UTC
Hi,
Haraka version 2.8.18
centos 6

Error
haraka -c /etc/haraka/
loaded TLD files: 1=1544 2=8347 3=2424
loaded 8447 Public Suffixes
loglevel: INFO
log format: DEFAULT
Starting up Haraka version 2.8.18
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: syslog
[CRIT] [-] [core] Compiling plugin: syslog failed
[CRIT] [-] [core] internal/modules/cjs/loader.js:550
[CRIT] [-] [core]     throw err;
[CRIT] [-] [core]     ^
[CRIT] [-] [core] 
[CRIT] [-] [core] Error: Cannot find module 'haraka-test-fixtures'
[CRIT] [-] [core]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
[CRIT] [-] [core]     at Function.Module._load (internal/modules/cjs/loader.js:475:25)
[CRIT] [-] [core]     at Module.require (internal/modules/cjs/loader.js:598:17)
[CRIT] [-] [core]     at require (internal/modules/cjs/helpers.js:11:18)
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/plugins.js:174:24
[CRIT] [-] [core]     at /etc/haraka/plugins/syslog.js:3:22
[CRIT] [-] [core]     at Script.runInContext (vm.js:74:29)
[CRIT] [-] [core]     at Script.runInNewContext (vm.js:80:15)
[CRIT] [-] [core]     at Object.runInNewContext (vm.js:193:38)
[CRIT] [-] [core]     at Plugin._compile (/usr/lib/node_modules/Haraka/plugins.js:237:16)

**Comment by msimerson** [comment] 2018-04-13 17:42
What is cjs?  It's doing something odd because this module **only** uses `haraka-test-fixtures` in its tests. Please follow up with your node.js version.

Closing for now, because I see no evidence that the problem is in this module or Haraka.

**Closed by msimerson** 2018-04-13 17:42 UTC
